name: database
description: database of Streetfood information system
version: 1.0.0
author: Michal Krůl

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  curl: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0